routes/web.php
<?php

use App\Http\Controllers\UserController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OngkirController;
use App\Http\Controllers\RateController;
use App\Http\Controllers\MailController;

use App\Http\Middleware\Authenticate;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/mail', 			'MailController@sendEmail');

Route::get('/', 				'HomeController@index');
Route::post('/',				'HomeController@item');
Route::get('/category/{name}', 	'HomeController@category');
Route::get('/item/{name}',		'HomeController@show');
Route::get('/about', 			'HomeController@about');

Route::get('/get_city/{id}',	'OngkirController@get_city');

Route::post('/get_cost',	'OngkirController@get_cost');

Route::group(['middleware' => ['auth']], function () {

	// Route::post('/add/{id}', 				'OrderController@create');
	Route::delete('/cart/{id}',				'OrderController@destroy');
	Route::get('/cart',			 			'OrderController@indexCustomer');
	Route::post('/cart',			 		'OrderController@store');
	Route::post('/checkout/order_id/{id}', 	'HomeController@COview');
	Route::put('/checkout/order_id/{id}', 	'HomeController@update');
	Route::get('/rate/create/item_{id}',	'RateController@create');
	Route::post('/rate/create/item_{id}',	'RateController@store');



	Route::post('/logout', 					'UserController@logout');
	Route::get('/logout', 					'UserController@logout');

	Route::group(['middleware' => ['isAdmin']], function () {
    Route::get('/dashboard', 				'HomeController@dashboard');
	Route::resource('/dashboard/rate', 		'RateController');
    Route::resource('/dashboard/category', 	'CategoryController');
    Route::resource('/dashboard/item', 		'ItemController');
	Route::resource('/dashboard/order',	 	'OrderController');
	Route::resource('/dashboard/profile', 	'ProfileController');
	Route::resource('/dashboard/user', 		'UserCrudController');
	Route::get('/dashboard/profile/create/{id}', 		'UserCrudController@createprofile');
	});
    Route::resource('/profile', 		'HomeProfileController');
    Route::get('/akun','HomeProfileController@account');
    Route::put('/akun','HomeProfileController@account_save');
});


// Login, Register, Logout
Route::group(['middleware' => ['guest']], function () {
	Route::get('/signin', 	'UserController@loginView')->name('login');
	Route::post('/signin', 	'UserController@login');

	Route::get('/signup', 	'UserController@registerView');
	Route::post('/signup',	'UserController@register');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','isAdmin','isActive'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $users = [
        'email_verified_at' => 'datetime',
    ];
    public function profile(){
        return $this->hasOne('App\Profile');
    }
    public function orders(){
        return $this->hasMany('App\Order');
    }
    public function rates(){
        return $this->hasMany('App\Rate');
    }
    public function getRoleDisplayAttribute(){
        if (@$this->attributes['isAdmin'] == 1) return 'Admin';
        if (@$this->attributes['isAdmin'] == 0) return 'Customer';
        return '-';
    }
    public function getStatusDisplayAttribute(){
        if (@$this->attributes['isActive'] == 1) return 'Active';
        if (@$this->attributes['isActive'] == 0) return 'Nonactive';
        return '-';
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\MailController;

class UserController extends Controller
{
    function loginView(){
        return view('auth.login');
    }
    function registerView() {
        return view('auth.register');
    }
    function register(Request $request){
        $validatedData = $request->validate([
            'name'      => 'required|min:8|max:45',
            'email'     => 'required|email:dns|unique:users',
            'password'  => 'required|min:8'
        ]);
        $validatedData['password']  = Hash::make($validatedData['password']);
        User::create($validatedData);
        MailController::registerEmail($validatedData['email']);
        return redirect('/signin');
    }
    public function login(Request $request){
        $validatedData = $request->validate([
            'email'=>'required',
            'password'=>'required'
        ]);
        if(Auth::attempt($validatedData)){
            $request->session()->regenerate();
            if (auth()->user()->isActive != 0) {
                if (auth()->user()->profile != null) {
                    return redirect()->intended('/');
                }else{
                    return redirect()->intended('/profile/create');
                }
            }else{
                Auth::logout();
                $request->session()->invalidate();
                $request->session()->regenerateToken();
                return back()->with('error','Akun anda dinonaktifkan, hubungi admin untuk mengaktifkan kembali akun anda!');
            }
        }
        return back()->with('error','Email atau Password anda salah!');

    }
    public function logout(Request $request){
        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();
        return redirect('/');
    }
    public function index(){
        Auth::user->id();
        return view('modul.profile.index-profile', compact('profile'));
      }

}

resources/views/modul/user/create-user.blade.php
@extends('master')
@section('title')
	Tambah User
@endsection
@section('content')
@include('part.feedback')
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary d-sm-flex align-items-center justify-content-between">
        <h6 class="h5 m-0 font-weight-bold text-gray-100">Tambah User</h6>
        <div class="d-inline-block">
            <a href="{{ url('dashboard/user') }}" class="btn btn-sm btn-danger shadow-sm"><i class="fa fa-undo"></i> Back</a>
        </div>
    </div>
    <div class="card-body">
        <div class="form">
            <form action="/dashboard/user" method="post" enctype="multipart/form-data">
				@csrf
				<div class="form-group">
					<label for="name">Username :</label>
					<input type="text" name="name" id="name" class="form-control">
				</div>
				<div class="form-group">
					<label for="email">Email :</label>
					<input type="text" name="email" id="email" class="form-control">
				</div>
				<div class="form-group">
					<label for="password">Password :</label>
					<input type="password" name="password" id="password" class="form-control">
				</div>
				<div class="form-group">
					<label for="isAdmin">Role</label>
					<select name="isAdmin" id="isAdmin" class="form-control select2">
						<option>-- Pilih Role --</option>
						<option value="1">Admin</option>
						<option value="0">Customer</option>
					</select>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-primary"><i class="fas fa-save"></i>Simpan</button>
				</div>
			</form>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
    $(document).ready(function() {
    $('.select2').select2();
});
</script>
@endpush

@push('style')

@endpush

resources/views/modul/user/edit-user.blade.php
@extends('master')
@section('title')
	Edit User
@endsection
@section('content')
@include('part.feedback')
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary d-sm-flex align-items-center justify-content-between">
        <h6 class="h5 m-0 font-weight-bold text-gray-100">Edit User</h6>
        <div class="d-inline-block">
            <a href="{{ url('dashboard/user') }}" class="btn btn-sm btn-danger shadow-sm"><i class="fa fa-undo"></i> Back</a>
        </div>
    </div>
    <div class="card-body">
        <div class="form">
            <form action="/dashboard/user/{{ $user->id }}" method="post" enctype="multipart/form-data">
				@csrf
                @method('put')
				<div class="form-group">
					<label for="name">Username :</label>
					<input type="text" name="name" id="name" class="form-control" value="{{ $user->name }}">
				</div>
				<div class="form-group">
					<label for="email">Email :</label>
					<input type="text" name="email" id="email" class="form-control" value="{{ $user->email }}">
				</div>
				<div class="form-group">
					<label for="password">New Password :</label>
					<input type="password" name="password" id="password" class="form-control">
				</div>
				<div class="form-group">
					<label for="isAdmin">Role</label>
					<select name="isAdmin" id="isAdmin" class="form-control select2">
						<option>-- Pilih Role --</option>
						<option value="1" {{ @$user->isAdmin == 1 ? 'selected' : ''}}>Admin</option>
						<option value="0" {{ @$user->isAdmin == 0 ? 'selected' : ''}}>Customer</option>
					</select>
				</div>
                <div class="form-group">
					<label for="isActive">Status</label>
					<select name="isActive" id="isActive" class="form-control select2">
						<option>-- Pilih Role --</option>
						<option value="1" {{ @$user->isActive == 1 ? 'selected' : ''}}>Active</option>
						<option value="0" {{ @$user->isActive == 0 ? 'selected' : ''}}>Nonactive</option>
					</select>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-primary"><i class="fas fa-save"></i>Simpan</button>
				</div>
			</form>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
    $(document).ready(function() {
    $('.select2').select2();
});
</script>
@endpush

@push('style')

@endpush

resources/views/modul/user/index-user.blade.php
@extends('master')
@section('title')
	User
@endsection
@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary d-sm-flex align-items-center justify-content-between">
        <h6 class="h5 m-0 font-weight-bold text-gray-100">List User</h6>
        <div class="d-inline-block">
            <a href="{{ url('dashboard/user/create') }}" class="btn btn-sm btn-success shadow-sm"><i class="fa fa-plus"></i> Tambah</a>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover" style="overflow: auto;">
                <thead>
                    <tr>
                        <td>No</td>
                        <td>Nama</td>
                        <td>Email</td>
                        <td>Role</td>
                        <td>Status</td>
                        <td>Aksi</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($user as $item)
                    <tr>
                        <td>{{ !empty($i) ? ++$i : $i = 1 }}</td>
                        <td>{{$item->name}}</td>
                        <td>{{$item->email}}</td>
                        <td>{{$item->role_display}}</td>
                        <td>{{$item->status_display}}</td>
                        <td>
                            <form action="/dashboard/user/{{$item->id}}" method="post">
                                <a href="/dashboard/user/{{$item->id}}" class="btn btn-info"><i class="fas fa-eye"></i></a>
                                <a href="/dashboard/user/{{$item->id}}/edit" class="btn btn-primary"><i class="fas fa-edit"></i></a>
                                @csrf
                                @method('delete')
                                @if ($item->isActive != 0)
                                <button type="submit" class="btn btn-danger"><i class="fas fa-power-off"></i></button>
                                @else
                                <button type="submit" class="btn btn-success"><i class="fas fa-power-off"></i></button>
                                @endif
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
              </table>

        </div>
    </div>
</div>
@endsection
@push('scripts')

@endpush
@if(session('success'))

  @push('scripts')
  <script>
    {!! session('success') !!}

  </script>

  @endpush
@endif

resources/views/modul/user/show-user.blade.php
@extends('master')
@section('title')
	Detail User
@endsection
@section('content')
{{-- @include('part.feedback') --}}
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary d-sm-flex align-items-center justify-content-between">
        <h6 class="h5 m-0 font-weight-bold text-gray-100">Detail User ID {{ $user->id }}</h6>
        <div class="d-inline-block">
            <a href="{{ url('dashboard/user') }}" class="btn btn-sm btn-danger shadow-sm"><i class="fa fa-undo"></i> Back</a>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-stripped" style="overflow: auto;">
                <tbody>
                    <tr>
                        <td colspan="3"><h3>Akun :</h3></td>
                    </tr>
                    <tr>
                        <td>Username </td>
                        <td> :</td>
                        <td> {{$user->name}}</td>
                    </tr>
                    <tr>
                        <td>Email </td>
                        <td> :</td>
                        <td> {{$user->email}}</td>
                    </tr>
                    <tr>
                        <td>Role</td>
                        <td> :</td>
                        <td> {{$user->role_display}}</td>
                    </tr>
                    <tr>
                        <td>Status</td>
                        <td> :</td>
                        <td> {{$user->status_display}}</td>
                    </tr>
                    <tr>
                        <td colspan="3"><h3>Profil :</h3></td>
                    </tr>
                    @if(!empty($profile))
                    <tr>
                        <td>Nama Lengkap</td>
                        <td> :</td>
                        <td> {{$profile->nama_lengkap}}</td>
                    </tr>
                    <tr>
                        <td>Foto</td>
                        <td> :</td>
                        <td>
                            <img src="\img\profile\{{ $profile->foto }}" alt="" width="50%">
                        </td>
                    </tr>
                    <tr>
                        <td>No HP</td>
                        <td> :</td>
                        <td> {{$profile->no_hp}}</td>
                    </tr>
                    <tr>
                        <td>Provinsi</td>
                        <td> :</td>
                        <td>
                            @foreach($provinces as $provinsi)
                            @if($provinsi['province_id']==$profile->provinsi)
                                {{$provinsi['province']}}
                            @endif
                            @endforeach
                        </td>
                    </tr>
                    <tr>
                        <td>Kota</td>
                        <td> :</td>
                        <td>
                            @foreach($cities as $kota)
                            @if($kota['city_id']==$profile->kota)
                              {{$kota['city_name']}}
                            @endif
                          @endforeach
                        </td>
                    </tr>
                    <tr>
                        <td>Alamat </td>
                        <td> :</td>
                        <td> {{$profile->alamat}}</td>
                    </tr>
                    @endif
                    @if(empty($profile))
                    <tr>
                        <td colspan="3">
                            <a href="{{ url('dashboard/profile/create/'.$user->id) }}" class="btn btn-sm btn-success shadow-sm"><i class="fa fa-plus"></i> Tambah Profile</a>
                        </td>
                    </tr>
                    @else
                    <tr>
                        <td colspan="3">
                            <a href="{{ url('dashboard/profile/'.$profile->id.'/edit') }}" class="btn btn-sm btn-success shadow-sm"><i class="fa fa-pen"></i> Update Profile</a>
                        </td>
                    </tr>
                    @endif
                </tbody>
              </table>

        </div>
    </div>
</div>
@endsection

@if(session('success'))

  @push('scripts')
  <script>
    {!! session('success') !!}

  </script>

  @endpush
@endif